### ISSUE TITLE
Error saving data to path with whitespaces

### ISSUE THREAD

**Issue by BeeWise** [skelpo/Storage#1]
Whenever I try to save some data to a path that contains whitespaces (for example, "/Users/user/Documents/Projects/Test App"), I get the following error: `"⚠️ [StorageError.fdErr: Received error code -1 when creating the new file]"`. I have tried to save the data to other paths that do not contain whitespaces and it works every time.

**Comment by calebkleveter** [comment]
How exactly are you trying to create the file? I was able to create a file in a path with whitespace without issues. If you post here exactly what you are doing, I'll try to reproduce the issue. Thanks!

**Comment by BeeWise** [comment]
```
do {
    let filename = "image.jpeg"
    let path = DirectoryConfig.detect().workDir + "Public/images" 
    let storage = try request.storage()
    let file = File(data: data, filename: filename)
    
    let future = storage.store(file: file, at: path)
    future.whenSuccess { url in
        promise.succeed(result: url)
    }
    
    future.whenFailure({ error in
        promise.fail(error: error)
    })
} catch let error {
    promise.fail(error: error)
}
```
`try request.storage()` returns `return try self.make(LocalStorage.self)`.

DirectoryConfig.detect().workDir is a path that contains a whitespace. If I replace `path` with `FileManager.default.currentDirectoryPath` or any other path without whitespaces, it will save the data correctly there.

**Comment by calebkleveter** [comment]
What is the full path that you are trying to save to?

**Comment by BeeWise** [comment]
Here is the path for which I cannot save the data:
`/Users/beewise/Documents/Projects/Bee Wise Team/server-swift/TestApp/Public/images`

Here are some paths for which I have successfully saved the data:
`/Users/beewise/Library/Developer/Xcode/DerivedData/TestApp-edldmlkuddzotmcprvohdxnfpvuw/Build/Products/Debug`
`/Users/beewise/Downloads`

**Comment by calebkleveter** [comment]
I was able to get the error when I escaped the spaces in the path:

```swift
try storage.store(file: file, at: FileManager.default.currentDirectoryPath + "/Test\\ Files\\ Dir")
```

Could your issue be related to that?

**Comment by BeeWise** [comment]
Might be, I don't know. I'm not escaping any spaces in my path.

**Comment by calebkleveter** [comment]
About all I know is that the error is occurring here: https://github.com/skelpo/Storage/blob/master/Sources/Storage/LocalStorage.swift#L125-L128. I'll dig around a bit more when I get a chance.

**Comment by BeeWise** [comment]
Have you tried `FileManager`'s `createFile(atPath:contents:attributes:)` method?

**Comment by calebkleveter** [comment]
That method works with the paths I was using before:

```swift
try FileManager.default.createDirectory(atPath: FileManager.default.currentDirectoryPath + "/Test Files", withIntermediateDirectories: false, attributes: nil)
FileManager.default.createFile(atPath: FileManager.default.currentDirectoryPath + "/Test Files/test.md", contents: self.data, attributes: nil)
```

**Comment by calebkleveter** [comment]
Maybe you don't have proper permissions set for the `/Users/beewise/Documents/Projects/Bee Wise Team/server-swift/TestApp/Public/images` directory?

**Comment by BeeWise** [comment]
I have the proper permissions for `/Users/beewise/Documents/Projects/Bee Wise Team/server-swift/TestApp/Public` (Read & Write). Here's another case where I can't save the data: `/Users/beewise/Downloads/Test File`, whereas I can save the data for this path: `/Users/beewise/Downloads/Test`. I don't think it's about permissions.

**Comment by calebkleveter** [comment]
Can you try to get any more information on this error? Right now we don't have a whole lot to work with.

**Comment by BeeWise** [comment]
How would I get any more information about that error?

**Comment by BeeWise** [comment]
If I use `FileManager.default.createFile`, it works every single time with any kind of path, with or without whitespaces.

**Comment by calebkleveter** [comment]
After line 125 in the `LocalStorage.swift` file, where the `fd` value is created, add:

```swift
print(errno)
```

And run the operation again. What is the value you get back?

**Comment by BeeWise** [comment]
I get the value of `2`.

**Comment by calebkleveter** [comment]
Sorry, that was wrong. It should look like this:

```swift
let fd = open(name, O_RDWR | O_TRUNC | O_CREAT, 0o644)
guard fd >= 0 else {
    print(errno)
    throw StorageError(identifier: "fdErr", reason: "Received error code \(fd) when creating the new file")
}
```

**Comment by BeeWise** [comment]
Yes, I receive the same value of `2`.

**Comment by calebkleveter** [comment]
Is that when the file create fails?

**Comment by BeeWise** [comment]
Yes, it's when it throws that `StorageError`. I've put `print(errno)` right before it throws the error, just like you said.

**Comment by calebkleveter** [comment]
Does the full directory exist that you are trying to create the file in? Because `LocalStorage` will _not_ create intermediate directories.

**Comment by calebkleveter** [comment]
Also, what system are you on?

**Comment by BeeWise** [comment]
No, it does not exists. But even if I want to save it on a folder that does exist, like `../Public`, it will still throw that error.

**Comment by BeeWise** [comment]
macOS Mojave, version 10.14 (18A391).

**Comment by calebkleveter** [comment]
If you don't mind, can you double check and make sure you get the same `errno` code when you try to create the file in a directory that does exist?

**Comment by BeeWise** [comment]
OK. Let me double check that.

**Comment by BeeWise** [comment]
You're right, now it works. I forgot to remove a path component.

**Comment by calebkleveter** [comment]
Woo! Glad we got that sorted out!

**Comment by BeeWise** [comment]
Why doesn't the `LocalStorage` handle the intermediate directories as well?

**Comment by calebkleveter** [comment]
It should. I'll release a patch for that in a few minutes.

**Comment by BeeWise** [comment]
OK, thanks.
